### ISSUE TITLE
mobile view: video frame x 3

### ISSUE THREAD

**Issue by emmadolphe** [kfactory-dev/kf-website#15]
when clicking on mobile view this is what I see - the video frame is replicated three times
![File](https://user-images.githubusercontent.com/97906265/151145883-6161584f-40fc-46dd-9f29-dc96f0841188.jpg)
.

**Comment by mpontus** [comment]
Can you tell your device model and browser? Does the issue persist under different orientation?

**Comment by emmadolphe** [comment]
1. Device / Model: iPhone7
2. Browser: Safari
3. Indeed: horizontally I only see one (1) frame

**Comment by mpontus** [comment]
Fixed in #16
